# multi_run:
#   task1: # 会覆盖到本体的参数
#     codec_args:
#       mode: 1
#   task2:
#     codec_args:
#       mode: 2

load:
  path: /mnt/netdisk2/sunsf/Code/MPCompress-merge/ckpt/cavc/detect_best.pth
  strict: false
  rules:
    - ["startswith", "dino.model", "useless"]
    # - ["startswith", "dino.feature_model", "dino.model"]
    # - ["startswith", "post_reg_tokens", "dino_codec.post_reg_tokens"]
    # - ["startswith", "pre_vit_blocks.", "dino_codec.pre_vit_blocks."]
    # - ["startswith", "post_vit_blocks.", "dino_codec.post_vit_blocks."]
    # - ["startswith", "f_a.", "dino_codec.f_a."]
    # - ["startswith", "f_s.", "dino_codec.f_s."]
    # - ["startswith", "latent_codec.hyper.", "dino_codec.hyper_lc."]
    # - ["startswith", "latent_codec.y.", "dino_codec.y_lc."]


model: 
  type: CAVCodec
  prompt_dim: 128
  feature_dim: 512
  compress_feature_dim: 64
  cond_tcm:
    type: CondTCM
    config: [2, 2, 2, 2, 2, 2]
    head_dim: [8, 16, 32, 32, 16, 8]
    drop_path_rate: 0.0
    N: 64
    M: 320
    num_slices: 5
    max_support_slices: 5
    setup_feature_extractor_fn: setup_vgg_feature_extractor
    feature_extract_fn: feature_extract
    
  fixed_scale: 1.0
  ffmpeg_path: /mnt/netdisk/车网_sandwich/traffic-network/Restormer/ffmpeg-7.0.2-amd64-static/ffmpeg
  ffmpeg_verbose: True

codec_args:
  mode: 3
