# multi_run:
#   task1: # 会覆盖到本体的参数
#     codec_args:
#       mode: 1
#   task2:
#     codec_args:
#       mode: 2

PROJECT_ROOT: ${oc.env:PROJECT_ROOT}

load:
  path: ${PROJECT_ROOT}/weights/cavc/lpips_best.pth
  strict: false
  rules: # type, pattern, replacement
    # - ["startswith", "dino.model", "useless"]


model: 
  type: CAVCodec
  prompt_dim: 128
  feature_dim: 512
  compress_feature_dim: 64
  cond_tcm:
    type: CondTCM
    config: [2, 2, 2, 2, 2, 2]
    head_dim: [8, 16, 32, 32, 16, 8]
    drop_path_rate: 0.0
    N: 64
    M: 320
    num_slices: 5
    max_support_slices: 5
    setup_feature_extractor_fn: setup_vgg_feature_extractor
    feature_extract_fn: feature_extract
    
  fixed_scale: 1.0
  ffmpeg_path: ffmpeg
  ffmpeg_verbose: True

codec_args:
  mode: 3
