multi_run:
  q001:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v3-small/Q1.0/runner.best.pth.tar
  q003:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v3-small/Q3.0/runner.best.pth.tar
  q006:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v3-small/Q6.0/runner.best.pth.tar
  q012:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v3-small/Q12.0/runner.best.pth.tar
  q024:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v3-small/Q24.0/runner.best.pth.tar
  q048:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v3-small/Q48.0/runner.best.pth.tar
  q096:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v3-small/Q96.0/runner.best.pth.tar
  q192:


load:
  path: /home/faymek/MPCompress/exp/archieve/MPC2-formal-y48-z48-slot-3/Q3.0/runner.best.pth.tar
  strict: false
  rules: # type, pattern, replacement
    - ["startswith", "dino.model", "useless"]

model: 
  type: MPC_I2
  
  dino_backbone:
    type: mpcompress.backbone.Dinov2TimmBackbone
    model_size: small
    img_size: 512
    patch_size: 16
    dynamic_size: true
    slot: -3
    n_last_blocks: 4

  dino_codec:
    type: mpcompress.latent_codecs.vit_feature_codec.VitUnionLatentCodec
    h_dim: 384
    y_dim: 48
    z_dim: 48
    groups: 16

allow_heads:
  - imagenet_cls_small_last4
  - voc2012_seg_small_last4
  - ade20k_seg_small_last4