model: 
  type: Dinov2TimmNoCompress
  
  dino_backbone:
    model_size: small
    img_size: 512
    patch_size: 16
    dynamic_size: true
    slot: -4
    n_last_blocks: 4

allow_heads:
  - imagenet_cls_small_last4
  - voc2012_seg_small_last4
  - ade20k_seg_small_last4