multi_run:
  q003:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v2/Q3.0/runner.best.pth.tar
  q006:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v2/Q6.0/runner.best.pth.tar
  q012:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v2/Q12.0/runner.best.pth.tar
  q024:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v2/Q24.0/runner.best.pth.tar
  q048:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v2/Q48.0/runner.best.pth.tar
  q096:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v2/Q96.0/runner.best.pth.tar
  q192:
    load:
      path: /home/faymek/MPCompress/exp/MPC2-v2/Q192.0/runner.best.pth.tar


load:
  path: /home/faymek/MPCompress/exp/MPC2-v2/Q3.0/runner.best.pth.tar
  strict: true
  rules: # type, pattern, replacement

model: 
  type: MPC_I2
  
  dino_backbone:
    model_size: small
    img_size: 512
    patch_size: 16
    dynamic_size: true
    slot: -4
    n_last_blocks: 4

  dino_codec:
    h_dim: 384
    y_dim: 48
    z_dim: 192
    groups: 16

allow_heads:
  - imagenet_cls_small_last4
  - voc2012_seg_small_last4
  - ade20k_seg_small_last4