PROJECT_ROOT: ${oc.env:PROJECT_ROOT}

extract:
  name: MPC12-v3-large-extract
  save_x_uint8: false
  batch_size: null  # if null, no batch dimension  
  split_size:
    train: 100  # the unit is batch
    val: 100

train_dataset:
  type: ImageFolder
  root: /home/faymek/Datasets/IN1K
  # root: ${PROJECT_ROOT}/data/IN1K
  split: train

val_dataset:
  type: ImageFolder
  root: /home/faymek/Datasets/IN1K
  # root: ${PROJECT_ROOT}/data/IN1K
  split: test_small

train_transforms:
  type: Compose
  transforms:
    - type: RandomCrop
      size: 512
      pad_if_needed: true
    - type: ToTensor

val_transforms:
  type: Compose
  transforms:
    - type: CenterCrop
      size: 512
    - type: ToTensor

model:
  type: MPC_I12

  vqgan_backbone:
    ckpt_path: ${PROJECT_ROOT}/weights/MPC/VQGAN-kmeans-cb1024.ckpt
    n_embed: 1024
    embed_dim: 256
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0

  vqgan_codec:
    type: UniformTokenCodec
    alphabet_size: 1024

  dino_backbone:
    model_size: large
    img_size: 512
    patch_size: 16
    dynamic_size: true
    slot: -3
    n_last_blocks: 4

  dino_codec:
    h_dim: 1024
    y_dim: 48
    z_dim: 48
    ctx_dim: 256
    groups: 16


  
