multi_run:
  62:
  57:
  52:
  47:
  42:
  37:
  32:
  27:
  22:

PROJECT_ROOT: ${oc.env:PROJECT_ROOT}

model: 
  type: Dinov2OrigSlideOnlyPatchCodec
  slide_size: [518, 518]
  slide_stride: [259, 259]

  dino_backbone:
    # type: Dinov2OrgBackbone
    model_size: giant
    img_size: 518
    patch_size: 14
    dynamic_size: false
    slot: null
    n_last_blocks: 1
    ckpt_path: ${PROJECT_ROOT}/weights/dinov2/backbone/dinov2_vitg14_pretrain.pth

  dino_codec:
    # type: VtmFeatureCodec
    cfg:
      vtm_path: ${PROJECT_ROOT}/weights/std_codec/VTM-21.0
      model_type: dinov2
      task: seg
      max_v: 103.2168
      min_v: -530.9767
      trun_high: 20
      trun_low: -20
      trun_flag: true
      quant_samples: 0
      quant_type: uniform
      bit_depth: 10 

allow_heads:
  - imagenet_cls_giant_last1
  - voc2012_seg_giant_last1