# Config for lamofc cls bypass (no compression) - testing baseline cls

multi_run:
  1.0:

PROJECT_ROOT: ${oc.env:PROJECT_ROOT}

resolution_transform:
  type: ResolutionTransform
  mode: resize
  size: [224, 224]

model:
  type: Dinov2OrigClsBypass

  dino_backbone:
    model_size: giant
    img_size: 224
    patch_size: 14
    dynamic_size: false
    slot: null
    n_last_blocks: 1
    ckpt_path: ${PROJECT_ROOT}/weights/dinov2/backbone/dinov2_vitg14_pretrain.pth

allow_heads:
  - imagenet_cls_giant_last1
