model_type: llama3
task: csr
max_v: 47.75
min_v: -78
trun_high: 5
trun_low: -5

lambda_value_all: [0.01405, 0.0142, 0.015, 0.07, 10]
epochs: 200
learning_rate: "1e-4"
batch_size: 40
patch_size: "64 4096"
trun_flag: true
quant_type: uniform
samples: 0
bit_depth: 1 