model_type: sd3
task: tti
max_v: 4.668
min_v: -6.176
trun_high: 4.668
trun_low: -6.176

lambda_value_all: [0.005, 0.01, 0.02, 0.05, 0.2]
epochs: 60
learning_rate: "1e-4"
batch_size: 32
patch_size: "512 512"
trun_flag: true
quant_type: uniform
samples: 0
bit_depth: 1 